#FROM openjdk:8-jdk
FROM docker.prod.walmart.com/samstechinfra/alpine-nginx-jdk:0.1.5
MAINTAINER spachip@walmart.com

ARG jarFileName

#RUN apt-get update \
#    && apt-get install -y --no-install-recommends openssh-server \
#    && echo "root:Docker!" | chpasswd

EXPOSE 8080 2222

#COPY sshd_config /etc/ssh/
COPY /src/main/resources/docker/proxy-intranet-ref-app.conf /etc/nginx/conf.d/proxy.conf
COPY /src/main/resources/docker/startup.sh /home/.
RUN chmod 755 /home/startup.sh
COPY $jarFileName /home/catalog-extractor.jar

ENTRYPOINT ["/home/startup.sh"]
